### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by vlordier** [Shakurova/LexicalTextSimplification#1]
There is an issue with np or something, see below

`(LexicalTextSimplification) mac:LexicalTextSimplification xxx$ python3 text_simplification.py 
2018-08-09 05:34:09,504 : INFO : loading projection weights from ./model/GoogleNews-vectors-negative300-SLIM.bin
2018-08-09 05:34:16,682 : INFO : loaded (299567, 300) matrix from ./model/GoogleNews-vectors-negative300-SLIM.bin
2018-08-09 05:34:18,509 : INFO : precomputing L2-norms of word weight vectors
/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):
Traceback (most recent call last):
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 609, in _read
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "text_simplification.py", line 249, in <module>
    simplified0, simplified1, simplified2 = simplifier.simplify(input)
  File "text_simplification.py", line 164, in simplify
    for option in self.generate_word2vec_candidates(difficultWord):
  File "text_simplification.py", line 75, in generate_word2vec_candidates
    converted = convert(option[0].lower(), word)
  File "/Users/xxx/LexicalTextSimplification/conjugation.py", line 17, in convert
    if tag(word_to)[0][1] == 'VBD':
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/en/__init__.py", line 188, in tag
    for sentence in parse(s, tokenize, True, False, False, False, encoding, **kwargs).split():
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/en/__init__.py", line 169, in parse
    return parser.parse(s, *args, **kwargs)
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 1172, in parse
    s[i] = self.find_tags(s[i], **kwargs)
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/en/__init__.py", line 114, in find_tags
    return _Parser.find_tags(self, tokens, **kwargs)
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 1113, in find_tags
    lexicon = kwargs.get("lexicon", self.lexicon or {}),
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 376, in __len__
    return self._lazy("__len__")
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 368, in _lazy
    self.load()
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 625, in load
    dict.update(self, (x.split(" ")[:2] for x in _read(self._path) if len(x.split(" ")) > 1))
  File "/Users/xxx/LexicalTextSimplification/lib/python3.7/site-packages/pattern/text/__init__.py", line 625, in <genexpr>
    dict.update(self, (x.split(" ")[:2] for x in _read(self._path) if len(x.split(" ")) > 1))
RuntimeError: generator raised StopIteration`

**Comment by vlordier** [comment]
Seems to be related to https://github.com/clips/pattern/issues/243
